### PR TITLE
base: Add Chinese translations

### PR DESCRIPTION
**Pull request by JohnsonRan**

### CODE REVIEW

**Comment by jhonboy121** [comment]
Do not translate keyguard indication strings. Do it device side

**Comment by JohnsonRan** [comment]
> Do not translate keyguard indication strings. Do it device side

deleted.
device side? you mean sm8150-common?

**Comment by npv12** [comment]
> 
> device side? you mean sm8150-common?

yes

**Comment by JohnsonRan** [comment]
> > device side? you mean sm8150-common?
> 
> yes

eh, cant find it...

**Comment by npv12** [comment]
> 
> eh, cant find it...

https://github.com/FlamingoOS-Devices/device_oneplus_oneplus7pro/blob/A12.1/overlay/FlamingoOnePlus7ProSystemUI/res/values/strings.xml#L21

**Comment by JohnsonRan** [comment]
> > eh, cant find it...
> 
> https://github.com/FlamingoOS-Devices/device_oneplus_oneplus7pro/blob/A12.1/overlay/FlamingoOnePlus7ProSystemUI/res/values/strings.xml#L21

O,what about op7,seems there aint such strings
https://github.com/FlamingoOS-Devices/device_oneplus_oneplus7/tree/A12.1/overlay/FlamingoOnePlus7SystemUI/res/values

**Comment by jhonboy121** [comment]
> > > eh, cant find it...
> > 
> > 
> > https://github.com/FlamingoOS-Devices/device_oneplus_oneplus7pro/blob/A12.1/overlay/FlamingoOnePlus7ProSystemUI/res/values/strings.xml#L21
> 
> O,what about op7,seems there aint such strings https://github.com/FlamingoOS-Devices/device_oneplus_oneplus7/tree/A12.1/overlay/FlamingoOnePlus7SystemUI/res/values

yes you have to translate there, it's using the default strings from fwb for english locale

**Comment by jhonboy121** [comment]
The whole reasoning for disallowing translations in fwb for sysui is to make your job and mine too, easier. You won't have to bother about translating sysui strings for further rebases anymore since 99% is in FlamingoSystemUI , and the one's left here is not meant to be translated here. I can't mark it as non-translatable because it should be translated in device trees.

**Comment by JohnsonRan** [comment]
> The whole reasoning for disallowing translations in fwb for sysui is to make your job and mine too, easier. You won't have to bother about translating sysui strings for further rebases anymore since 99% is in FlamingoSystemUI , and the one's left here is not meant to be translated here. I can't mark it as non-translatable because it should be translated in device trees.

Can i translate keyguard indication [here](https://github.com/FlamingoOS-Devices/device_oneplus_sm8150-common/tree/A12.1/overlay/FlamingoOnePlusSM8150SystemUI/res/values)? because im using same strings in all devices.
Also,op7t and 7tpro seems doesnt have A13 branch yet

**Comment by jhonboy121** [comment]
> > The whole reasoning for disallowing translations in fwb for sysui is to make your job and mine too, easier. You won't have to bother about translating sysui strings for further rebases anymore since 99% is in FlamingoSystemUI , and the one's left here is not meant to be translated here. I can't mark it as non-translatable because it should be translated in device trees.
> 
> Can i translate keyguard indication [here](https://github.com/FlamingoOS-Devices/device_oneplus_sm8150-common/tree/A12.1/overlay/FlamingoOnePlusSM8150SystemUI/res/values)? because im using same strings in all devices. Also,op7t and 7tpro seems doesnt have A13 branch yet

No because op7 only have dash charging. Should not translate in common tree. Translate in op7 and op7pro for now, add translations when A13 branch is created in the rest of the repos, which should be soon enough

**Comment by JohnsonRan** [comment]
> > > The whole reasoning for disallowing translations in fwb for sysui is to make your job and mine too, easier. You won't have to bother about translating sysui strings for further rebases anymore since 99% is in FlamingoSystemUI , and the one's left here is not meant to be translated here. I can't mark it as non-translatable because it should be translated in device trees.
> > 
> > 
> > Can i translate keyguard indication [here](https://github.com/FlamingoOS-Devices/device_oneplus_sm8150-common/tree/A12.1/overlay/FlamingoOnePlusSM8150SystemUI/res/values)? because im using same strings in all devices. Also,op7t and 7tpro seems doesnt have A13 branch yet
> 
> No because op7 only have dash charging. Should not translate in common tree. Translate in op7 and op7pro for now, add translations when A13 branch is created in the rest of the repos, which should be soon enough

im translate all of it to "fast charging",because if someone using dash charger on op7p,it will show "warp charging" because of the strings,it looks weird

**Comment by jhonboy121** [comment]
Alright then

**Pull request merged**
